language: node_js
node_js:
  - "4"
  - "6"
sudo: false

script:
  - npm test
  - if ! git diff --patch --stat --color=never --exit-code; then
        echo "#### You can apply this patch via:" >&2;
        echo "git apply -" >&2;
        echo "git commit --all --message 'fix up generated files via `npm run build`'" >&2;
        false;
    fi
